// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectSite.Data;

#nullable disable

namespace ProjectSite.Migrations
{
    [DbContext(typeof(ProjectSiteContext))]
    [Migration("20241103134936_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProjectSite.Models.Restaurant", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("res_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Restaurant");
                });

            modelBuilder.Entity("ProjectSite.Models.Review", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int?>("assessment_of_the_atmosphere")
                        .HasColumnType("int");

                    b.Property<int?>("dessert_evaluation")
                        .HasColumnType("int");

                    b.Property<int?>("evaluation_of_snacks")
                        .HasColumnType("int");

                    b.Property<int?>("evaluation_of_the_first_courses")
                        .HasColumnType("int");

                    b.Property<int?>("evaluation_of_the_second_courses")
                        .HasColumnType("int");

                    b.Property<int>("id_restaurant")
                        .HasColumnType("int");

                    b.Property<int>("id_user")
                        .HasColumnType("int");

                    b.Property<int?>("service_assessment")
                        .HasColumnType("int");

                    b.Property<string>("total_review")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Review");
                });
#pragma warning restore 612, 618
        }
    }
}
